"""Domain foundation for ToolRecap V2 multi-episode analysis, commentary, and persistence."""
from __future__ import annotations

from .cache import (
    EvidenceCacheManager,
    HierarchyCacheManager,
    compute_batch_cache_key,
    compute_cache_key,
    compute_connection_cache_key,
    compute_finalizer_cache_key,
    compute_merge_cache_key,
    compute_source_identity_hash,
    compute_summary_cache_key,
    default_evidence_cache_dir,
    default_hierarchy_cache_dir,
    validate_finalizer_cache_data,
    validate_hierarchy_cache_data,
)
from .enums import (
    AnalysisScope,
    AudioPolicy,
    CandidateScope,
    CompactionLevel,
    OutputStatus,
    ProjectPhase,
)
from .models import (
    AnalysisManifest,
    CommentaryOutput,
    CompactEpisodeSummary,
    CompactSummaryItem,
    DomainError,
    EpisodeEvidence,
    MediaSelection,
    SUMMARY_SCHEMA_VERSION,
    Segment,
    SourceClip,
    SourceEpisode,
    ValidationError,
    build_compact_summary,
    compact_summary,
    split_summary_by_timeline,
)
from .title import resolve_unique_titles, sanitize_title

__all__ = [
    "AnalysisManifest",
    "AnalysisScope",
    "AudioPolicy",
    "CandidateScope",
    "CommentaryOutput",
    "CompactEpisodeSummary",
    "CompactSummaryItem",
    "CompactionLevel",
    "DomainError",
    "EpisodeEvidence",
    "EvidenceCacheManager",
    "HierarchyCacheManager",
    "MediaSelection",
    "OutputStatus",
    "ProjectPhase",
    "SUMMARY_SCHEMA_VERSION",
    "Segment",
    "SourceClip",
    "SourceEpisode",
    "ValidationError",
    "build_compact_summary",
    "compact_summary",
    "split_summary_by_timeline",
    "compute_batch_cache_key",
    "compute_cache_key",
    "compute_connection_cache_key",
    "compute_finalizer_cache_key",
    "compute_merge_cache_key",
    "compute_source_identity_hash",
    "compute_summary_cache_key",
    "default_evidence_cache_dir",
    "default_hierarchy_cache_dir",
    "resolve_unique_titles",
    "sanitize_title",
    "validate_finalizer_cache_data",
    "validate_hierarchy_cache_data",
]
