"""Candidate discovery and consolidation package for ToolRecap V2."""
from __future__ import annotations

from .consolidation import (
    CONSOLIDATION_ALGO_VERSION,
    CONSOLIDATION_PROMPT_VERSION,
    CandidateConsolidator,
    compact_candidate_payload,
    compute_candidate_similarity,
    compute_candidates_payload_hash,
    consolidate_candidates,
    estimate_consolidation_request_size,
    format_consolidation_node_user_text,
    pre_group_candidates,
    reconcile_and_validate_decisions,
    validate_consolidation_response_schema,
)
from .discovery import (
    CandidateDiscoverer,
    DiscoveryNodePlanItem,
    compute_coverage_hash,
    discover_candidates_season,
    discover_candidates_single,
    estimate_discovery_request_size,
    format_discovery_node_user_text,
    ground_validate_candidate,
    migrate_legacy_connection_candidates,
    plan_discovery_nodes,
    validate_discovery_response_schema,
)
from .verifier import (
    HARD_PAYLOAD_CEILING,
    TARGET_PAYLOAD_CEILING,
    VERIFIER_ALGO_VERSION,
    VERIFIER_PROMPT_VERSION,
    CandidateVerifier,
    classify_deterministic_reason,
    compute_health_hash,
    estimate_verification_request_size,
    format_verification_user_text,
    is_genuine_zero_valid,
    is_suspicious_low_coverage,
    should_trigger_verification,
    validate_recovered_candidates,
    validate_verification_response_schema,
    verify_zero_or_low_output,
)

__all__ = [
    "CONSOLIDATION_ALGO_VERSION",
    "CONSOLIDATION_PROMPT_VERSION",
    "CandidateConsolidator",
    "CandidateDiscoverer",
    "CandidateVerifier",
    "DiscoveryNodePlanItem",
    "HARD_PAYLOAD_CEILING",
    "TARGET_PAYLOAD_CEILING",
    "VERIFIER_ALGO_VERSION",
    "VERIFIER_PROMPT_VERSION",
    "classify_deterministic_reason",
    "compact_candidate_payload",
    "compute_candidate_similarity",
    "compute_candidates_payload_hash",
    "compute_coverage_hash",
    "compute_health_hash",
    "consolidate_candidates",
    "discover_candidates_season",
    "discover_candidates_single",
    "estimate_consolidation_request_size",
    "estimate_discovery_request_size",
    "estimate_verification_request_size",
    "format_consolidation_node_user_text",
    "format_discovery_node_user_text",
    "format_verification_user_text",
    "ground_validate_candidate",
    "is_genuine_zero_valid",
    "is_suspicious_low_coverage",
    "migrate_legacy_connection_candidates",
    "plan_discovery_nodes",
    "pre_group_candidates",
    "reconcile_and_validate_decisions",
    "should_trigger_verification",
    "validate_consolidation_response_schema",
    "validate_discovery_response_schema",
    "validate_recovered_candidates",
    "validate_verification_response_schema",
    "verify_zero_or_low_output",
]
