"""Analyzer package providing single and season AI analysis, episode evidence, and candidate mining."""
from __future__ import annotations

from .candidates import (
    CandidateConsolidator,
    CandidateDiscoverer,
    CandidateVerifier,
    consolidate_candidates,
    discover_candidates_season,
    discover_candidates_single,
    migrate_legacy_connection_candidates,
    verify_zero_or_low_output,
)
from .connection import (
    CandidateProposal,
    SeasonConnectionResult,
    SeasonConnector,
    partition_season_batches,
)
from .coverage import (
    CategoryCoverageRecord,
    CharacterCoverageRecord,
    ChunkCoverageRecord,
    CoverageGap,
    CoverageStatus,
    EpisodeCoverage,
    GapType,
    SecondPassRequest,
    TimelineCoverage,
    TimeRange,
    compute_episode_coverage,
    detect_coverage_gaps,
    merge_intervals,
    merge_second_pass_results,
    plan_second_pass_requests,
    subtract_intervals,
)
from .engine import AnalysisEngine, compute_final_plan_cache_key, run_analysis
from .errors import AnalysisCancelledError, AnalysisError, CoverageIncompleteError
from .evidence import (
    EVIDENCE_CATEGORIES,
    EvidenceScanner,
    compute_scanner_config_version,
)
from .finalizer import CandidateFinalizer
from .phases import AnalysisPhase, PhaseCallback
from .prompts import (
    CANDIDATE_CONSOLIDATION_SYSTEM_PROMPT,
    CANDIDATE_DISCOVERY_SYSTEM_PROMPT,
    FINALIZER_SYSTEM_PROMPT,
    SCANNER_GAP_SYSTEM_PROMPT,
    SCANNER_SYSTEM_PROMPT,
    SEASON_BATCH_SYSTEM_PROMPT,
    SEASON_CONNECTION_SYSTEM_PROMPT,
    SEASON_MERGE_SYSTEM_PROMPT,
)

__all__ = [
    "AnalysisCancelledError",
    "AnalysisEngine",
    "AnalysisError",
    "AnalysisPhase",
    "CandidateConsolidator",
    "CandidateDiscoverer",
    "CandidateFinalizer",
    "CandidateProposal",
    "CandidateVerifier",
    "CANDIDATE_CONSOLIDATION_SYSTEM_PROMPT",
    "CANDIDATE_DISCOVERY_SYSTEM_PROMPT",
    "CategoryCoverageRecord",
    "CharacterCoverageRecord",
    "ChunkCoverageRecord",
    "CoverageGap",
    "CoverageIncompleteError",
    "CoverageStatus",
    "EVIDENCE_CATEGORIES",
    "EpisodeCoverage",
    "EvidenceScanner",
    "FINALIZER_SYSTEM_PROMPT",
    "GapType",
    "PhaseCallback",
    "SCANNER_GAP_SYSTEM_PROMPT",
    "SCANNER_SYSTEM_PROMPT",
    "SEASON_BATCH_SYSTEM_PROMPT",
    "SEASON_CONNECTION_SYSTEM_PROMPT",
    "SEASON_MERGE_SYSTEM_PROMPT",
    "SeasonConnectionResult",
    "SeasonConnector",
    "SecondPassRequest",
    "TimelineCoverage",
    "TimeRange",
    "compute_episode_coverage",
    "compute_final_plan_cache_key",
    "compute_scanner_config_version",
    "consolidate_candidates",
    "detect_coverage_gaps",
    "discover_candidates_season",
    "discover_candidates_single",
    "merge_intervals",
    "merge_second_pass_results",
    "migrate_legacy_connection_candidates",
    "partition_season_batches",
    "plan_second_pass_requests",
    "run_analysis",
    "subtract_intervals",
    "verify_zero_or_low_output",
]
